### ISSUE TITLE
addPropType error

### ISSUE THREAD

**Issue by seba97352** [eliot-akira/proptypes-schema#2]
i am getting error : 
> TypeError: (0 , _propTypesCallable.createChainableTypeChecker) is not a function

after calling function addPropType

```
import { addPropType } from 'proptypes-schema'
 
addPropType('notEmpty', (value, propName, schemaName) => {
  if (!value) {
    return `'${propName}' is empty for '${schemaName}'.`
  }
})
```

**Comment by eliot-akira** [comment]
Thank you for letting me know, it should be fixed in the latest version 0.2.0.
